#!/usr/bin/env python3

import click

# requiress the `netifaces` package to be installed
from netifaces import AF_INET, ifaddresses

def ip4_addr(iface):
    return ifaddresses(iface)[AF_INET][0]['addr']

def update_hosts_file(ip, hosts):
    with open('/etc/hosts', 'r+') as hosts_file:
        lines = hosts_file.readlines()
        hosts_file.seek(0)  # Reset to head of file
        for line in filter(lambda l: l is not '\n', lines):
            # Keep the line if it doesn't contain our host
            if all(map(lambda host: host not in line, hosts)):
                hosts_file.write(line)
        hosts_file.truncate()   # Remove everything else
        for host in hosts:
            hosts_file.write(f'\n{ip} {host}')  # Write our dev entry

@click.command()
@click.option('-i', '--interface', type=str, default='wlp2s0',
              help='Network interface to bind to.')
@click.argument('hosts', type=click.File('r'))
def main(interface, hosts):
    ip_addr = ip4_addr(interface)
    hosts = list(filter(lambda x: x, hosts.read().split('\n')))
    update_hosts_file(ip_addr, hosts)

if __name__ == '__main__':
    main()
